### ISSUE TITLE
What's the big 500x500 image supposed to represent?

### ISSUE THREAD

**Issue by maximx1** [rikai/OpenYourMouth#118]
Is that supposed to be an image of the food? I wasn't sure and couldn't find anything about it with a quick search throughout the repo.

**Comment by rikai** [comment]
Yes, it is. :)

**Comment by maximx1** [comment]
Cool, going all git-instagram. Should we host the images externally or is there a planned structure to keep it within the repo?

**Comment by 19kestier** [comment]
Currently, people putting images in [their recipes](https://github.com/rikai/OpenYourMouth/blob/master/Eggs/EggSandwich.md) are just hosting the images on [Imgur](http://imgur.com).
