### ISSUE TITLE
Licensing: GPL vs. CC ShareAlike

### ISSUE THREAD

**Issue by ninjaaron** [rikai/OpenYourMouth#53]
It might be too late to make this change, but a code license like the GPL doesn't make much sense with artistic/cultural works like recipes, since it refers to a lot of technical things like source code, compiling, executing, software, etc. The [CC ShareAlike](http://creativecommons.org/licenses/by-sa/4.0/) would be the equivalent license for written (and other) works. It's free and it's viral.

**Comment by rikai** [comment]
I, personally, dislike v3 and see no benefit to using it on this project.

**Comment by rikai** [comment]
Right then, don't see much of a real need to change, so sticking with the GPLv2
